# Generated by Django 4.2.13 on 2024-05-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NOTES', '0003_uploadednotes_delete_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadednotes',
            old_name='uplodingdate',
            new_name='uploadingdate',
        ),
        migrations.AlterField(
            model_name='uploadednotes',
            name='notesfile',
            field=models.FileField(upload_to=''),
        ),
    ]
